### ISSUE TITLE
Question about Transformer

### ISSUE THREAD

**Issue by librarywebchic** [jiaola/marc4js#6]
Sorry if this is a newbie question. I'm trying to transform a record into "Text" and have that text be assigned to a variable as a string so I can return it in an HTML template. However I keep ending up with a TextTransformer object. I'm assuming this is because the transformation hasn't "finished". Suggestions on how to fix this.

    	let record_s = marc4js.transform(this.record, {toFormat: 'text'}, function(err, output) {
    		return output;
    	});
    	console.log(record_s);

**Comment by jiaola** [comment]
The output is accessible inside the callback function. Try this: 

```
	marc4js.transform(this.record, {toFormat: 'text'}, function(err, output) {
		console.log(output);
	});
```
